= yagisan-reports トライアル使用許諾規約
:page-type: terms

本規約は、デンキヤギ株式会社（以下「当社」という）とyagisan-reports（以下「本ソフトウェア」といい、ソフトウェア・媒体・マニュアルなどの関連書類および電子文書を含む）をダウンロードした者（以下「ユーザー」という）との間で、本ソフトウェアのトライアル使用の条件を定めるものである。ユーザーは、本ソフトウェアをトライアル使用するにあたり、本規約の内容に同意する必要がある。

== 第1条 本ソフトウェアのトライアル使用許諾

1. 当社は、ユーザーに対し、本規約記載の条件に基づいて、本ソフトウェアについて非独占的なトライアル使用を許諾する。

== 第2条 使用目的の制限

1. ユーザーは、本ソフトウェア及び本ソフトウェアの派生ソフトウェア（本ソフトウェアを利用して開発したソフトウェアをいう。以下同じ）を以下の目的・態様でのみ利用することができる。
[arabic]
.. 本ソフトウェア +
技術検証、機能評価、及び派生ソフトウェアの開発
.. 派生ソフトウェア +
派生ソフトウェアの技術検証、機能評価、及びデモ
2. ユーザーは、本ソフトウェア及び派生ソフトウェアを前項に定める以外の目的・態様（第三者への販売、及び第三者への有償・無償を問わない再利用許諾を含むがそれに限られない）で使用してはならない。

== 第3条 権利の制限

1. ユーザーは、別途明示的に承諾されている場合を除き、本ソフトウェアの全部または一部を譲渡、販売することはできず、再使用許諾、貸与またはリースその他の方法で第三者に使用させてはならない。
2. ユーザーは、別途明示的に承諾されている場合を除き、本ソフトウェアの一部またはその構成部分を本ソフトウェアから分離して使用してはならない。
3. ユーザーは、本ソフトウェアを用いて、当社または第三者の著作権等の権利を侵害する行為を行ってはならない。
4. ユーザーは、別途明示的に許諾されている場合を除き、本ソフトウェアに対する修正、翻案、翻訳等の改変を加えることはできない。また、本ソフトウェアに含まれるトレードマークやその他の権利標記等の表示を削除したり、外観の変更をしてはならない。
5. ユーザーは、本ソフトウェアに関しリバースエンジニアリング、逆アセンブル、逆コンパイル等のソースコード解析作業を行ってはならない。
6. ユーザーは、別途明示的に承諾されている場合を除き、yagisan-reportsと競合する製品やサービスを直接または間接的に開発、促進、サポートするために本ソフトウェアの全部または一部を使用してはならない。

== 第4条 知的財産権

1. 本ソフトウェアに関する著作権等一切の権利は、当社またはその他正当な権限を有する者（以下「原権利者」という）に帰属するものとし、ユーザーは本ソフトウェアに関して本契約に基づき許諾された使用権以外の権利を有しないものとする。

== 第5条 責任の範囲

1. 当社および原権利者は、本ソフトウェアにエラー、バグ等の不具合がないこと、もしくは本ソフトウェアが中断なく稼動することまたは本ソフトウェアの使用がユーザーおよび第三者に損害を与えないことを保証しない。また、当社および原権利者は、本ソフトウェアが第三者の知的財産権を侵害していないことを保証しない。
2. 本ソフトウェアの稼動が依存する可能性のある、本ソフトウェア以外の製品、ソフトウェアまたはネットワークサービス（当該製品、ソフトウェアまたはサービスは第三者が提供する場合に限られず、当社または原権利者が提供する場合も含む）は、当該ソフトウェアまたはネットワークサービスの提供者の判断で中止または中断する場合がある。当社および原権利者は、本ソフトウェアの稼動が依存する可能性のあるこれらの製品、ソフトウェアまたはネットワークサービスが中断なく正常に作動することおよび将来にわたって正常に稼動することを保証しない。

== 第6条 第三者に対する責任

1. ユーザーが本ソフトウェアを使用することにより、第三者との間で著作権、特許権その他の知的財産権の侵害に関する紛争その他第三者との間で何らかの紛争が発生したときは、ユーザー自身が自らの費用で解決するものとし、当社および原権利者に一切の迷惑をかけないものとする。
2. 前項にいう第三者との紛争に伴って当社または原権利者に損害が発生したときは、ユーザーは、当社または原権利者に生じた一切の損害を賠償する。

== 第7条 秘密情報等の取り扱い

1. 本契約における「秘密情報」とは、本ソフトウェアに関する全ての情報をいう。ただし、以下の情報は秘密情報の対象外とする。
[arabic]
.. 当社から秘密情報ではないことを明示された情報
.. 開示を受けたときに既に保有していた情報
.. 開示を受けた後、秘密保持義務を負うことなく第三者から正当に入手した情報
.. 開示を受けた後、当社から開示を受けた情報に関係なく独自に取得し、または創出した情報
.. 開示を受けたときに既に公知であった情報
.. 開示を受けた後、ユーザーの責めに帰し得ない事由により公知となった情報
2. ユーザーは、当社から開示を受けた秘密情報の取扱いについて、次の各号に定める事項を遵守する。
[arabic]
.. 情報取扱管理者を定め、当社から開示された秘密情報を、善良なる管理者としての注意義務をもって厳重に保管、管理する。
.. 秘密情報は、本ソフトウェアの評価目的以外には使用しないものとする。
.. 漏えい、紛失、盗難、盗用等の事態が発生し、またはそのおそれがあることを知った場合は、直ちにその旨を当社に書面または電磁的方法をもって通知する。
3. ユーザーは、秘密情報を第三者に開示する場合には、書面または電磁的方法により当社の事前承諾を得なければならない。この場合、ユーザーは、当該第三者との間で本契約書と同等の義務を負わせ、これを遵守させる義務を負うものとする。

== 第8条 輸出管理

1. ユーザーが本ソフトウェアを日本国外に持ち出す場合、日本国内外の輸出管理に関連する法規を遵守するものとする。

== 第9条 契約の終了

1. 当社は、ユーザーが以下の各号に規定する事由に該当した場合には、催告なく直ちに本契約を解除することができる。
[arabic]
.. 本契約（当社ユーザー間で別途合意された本契約に関する条件を含む）の各条項に違反したとき
.. 監督官庁より営業許可取消し、停止その他の行政処分を受けたとき
.. 支払不能又は支払停止の状態に陥ったとき
.. 自己振出の手形又は小切手が不渡りとなったとき
.. 差押え、仮差押え、仮処分、強制執行若しくは担保権の実行としての競売の申立て又は公租公課の滞納処分のあったとき
.. 破産手続開始、再生手続開始、更生手続開始、特別清算開始又は特別調停の申立てがあったとき
.. 解散、事業譲渡、会社分割、合併の決議があったとき、又は資本の減少、営業の廃止若しくは変更があったとき
.. 資産、信用又は支払能力に重大な変更を生じたとき
.. その他前各号に準ずる事由が生じたとき
2. 前項またはその他の事由で本契約が終了した場合でも、第2条から第11条の規定は有効に存続する。

== 第10条 本ソフトウェアの廃棄

1. 何らかの理由により本契約が終了したとき、ユーザーは速やかに本ソフトウェアおよびその複製物を廃棄する。

== 第11条 その他

1. 本契約は日本法に従って解釈されるものとする。
2. ユーザーが本契約に違反し当社に損害を与えた場合、ユーザーは、当社に生じた一切の損害を賠償する。
3. 本契約の一部の条項が法令に違反するとされた場合、当該条項は、その限りにおいて本契約に適用されないものとし、本契約の他の条項は引き続き有効に存続するものとする。
4. 本契約に関連する紛争については、名古屋地方裁判所を第一審専属合意管轄裁判所とする。

== 改定履歴

* 2024年4月25日 制定
* 本規約はGitHubにて改版管理を行っております。
** https://github.com/DenkiYagi/yagisan-reports-terms